package com.ifisolution.chesstournament.entity;
// Generated Oct 5, 2018 11:22:52 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;

/**
 * PlayerTournamentParticipation generated by hbm2java
 */
@Entity
@Table(name = "Actual_Tournament_Sponsors", catalog = "chess_tournament")
public class ActualTournamentSponsors implements java.io.Serializable {

    private ActualTournamentSponsorsId id;
    private ListOfSponsors listOfSponsors;
    private Tournaments tournaments;

    public ActualTournamentSponsors() {
    }

    public ActualTournamentSponsors(ListOfSponsors listOfSponsors, Tournaments tournaments) {
        this.listOfSponsors = listOfSponsors;
        this.tournaments = tournaments;
    }

    @EmbeddedId

    @AttributeOverrides({@AttributeOverride(name = "sponsorId", column = @Column(name = "sponsor_id", nullable = false)),
            @AttributeOverride(name = "tournamentId", column = @Column(name = "tournament_id", nullable = false))})
    public ActualTournamentSponsorsId getId() {
        return this.id;
    }

    public void setId(ActualTournamentSponsorsId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "sponsor_id", nullable = false, insertable = false, updatable = false)
    public ListOfSponsors getListOfSponsors() {
        return this.listOfSponsors;
    }

    public void setListOfSponsors(ListOfSponsors listOfSponsors) {
        this.listOfSponsors = listOfSponsors;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "tournament_id", nullable = false, insertable = false, updatable = false)
    public Tournaments getTournaments() {
        return this.tournaments;
    }

    public void setTournaments(Tournaments tournaments) {
        this.tournaments = tournaments;
    }


}
