package com.ifisolution.chesstournament.entity;
// Generated Oct 5, 2018 11:22:52 PM by Hibernate Tools 5.2.11.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ChessClubs generated by hbm2java
 */
@Entity
@Table(name = "chess_clubs", catalog = "chess_tournament")
@JsonIgnoreProperties({"tournamentOrganizerses", "playerses"})

public class ChessClubs implements java.io.Serializable {

	private Integer clubId;
	private String clubName;
	private String clubAddress;
	private String otherClubDetails;
	private String organizerId;
	private Set<TournamentOrganizers> tournamentOrganizerses = new HashSet<TournamentOrganizers>(0);
	private Set<Players> playerses = new HashSet<Players>(0);

	public ChessClubs() {
	}

	public ChessClubs(String clubName, String clubAddress, String otherClubDetails, String organizerId) {
		this.clubName = clubName;
		this.clubAddress = clubAddress;
		this.otherClubDetails = otherClubDetails;
		this.organizerId = organizerId;
	}

	public ChessClubs(String clubName, String clubAddress, String otherClubDetails, String organizerId,
			Set<TournamentOrganizers> tournamentOrganizerses, Set<Players> playerses) {
		this.clubName = clubName;
		this.clubAddress = clubAddress;
		this.otherClubDetails = otherClubDetails;
		this.organizerId = organizerId;
		this.tournamentOrganizerses = tournamentOrganizerses;
		this.playerses = playerses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "club_id", unique = true, nullable = false)
	public Integer getClubId() {
		return this.clubId;
	}

	public void setClubId(Integer clubId) {
		this.clubId = clubId;
	}

	@Column(name = "club_name", nullable = false)
	public String getClubName() {
		return this.clubName;
	}

	public void setClubName(String clubName) {
		this.clubName = clubName;
	}

	@Column(name = "club_address", nullable = false)
	public String getClubAddress() {
		return this.clubAddress;
	}

	public void setClubAddress(String clubAddress) {
		this.clubAddress = clubAddress;
	}

	@Column(name = "other_club_details", nullable = false)
	public String getOtherClubDetails() {
		return this.otherClubDetails;
	}

	public void setOtherClubDetails(String otherClubDetails) {
		this.otherClubDetails = otherClubDetails;
	}

	@Column(name = "organizer_id", nullable = false)
	public String getOrganizerId() {
		return this.organizerId;
	}

	public void setOrganizerId(String organizerId) {
		this.organizerId = organizerId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chessClubs")
	public Set<TournamentOrganizers> getTournamentOrganizerses() {
		return this.tournamentOrganizerses;
	}

	public void setTournamentOrganizerses(Set<TournamentOrganizers> tournamentOrganizerses) {
		this.tournamentOrganizerses = tournamentOrganizerses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chessClubs")
	public Set<Players> getPlayerses() {
		return this.playerses;
	}

	public void setPlayerses(Set<Players> playerses) {
		this.playerses = playerses;
	}

}
