package com.ifisolution.chesstournament.entity;
// Generated Oct 5, 2018 11:22:52 PM by Hibernate Tools 5.2.11.Final

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ListOfSponsors generated by hbm2java
 */
@Entity
@Table(name = "list_of_sponsors", catalog = "chess_tournament")
@JsonIgnoreProperties({"actualTournamentSponsors"})

public class ListOfSponsors implements java.io.Serializable {

	private Integer sponsorId;
	private String sponsorName;
	private String sponsorPhone;
	private String otherSponsorDetails;
	@JsonIgnore
	private Set<ActualTournamentSponsors> actualTournamentSponsors = new HashSet<ActualTournamentSponsors>(0);

	public ListOfSponsors() {
	}

	public ListOfSponsors(String sponsorName, String sponsorPhone, String otherSponsorDetails) {
		this.sponsorName = sponsorName;
		this.sponsorPhone = sponsorPhone;
		this.otherSponsorDetails = otherSponsorDetails;
	}

    public ListOfSponsors(Integer sponsorId, String sponsorName, String sponsorPhone, String otherSponsorDetails, Set<ActualTournamentSponsors> actualTournamentSponsors) {
        this.sponsorId = sponsorId;
		this.sponsorName = sponsorName;
		this.sponsorPhone = sponsorPhone;
		this.otherSponsorDetails = otherSponsorDetails;
        this.actualTournamentSponsors = actualTournamentSponsors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sponsor_id", unique = true, nullable = false)
	public Integer getSponsorId() {
		return this.sponsorId;
	}

	public void setSponsorId(Integer sponsorId) {
		this.sponsorId = sponsorId;
	}

	@Column(name = "sponsor_name", nullable = false)
	public String getSponsorName() {
		return this.sponsorName;
	}

	public void setSponsorName(String sponsorName) {
		this.sponsorName = sponsorName;
	}

	@Column(name = "sponsor_phone", nullable = false)
	public String getSponsorPhone() {
		return this.sponsorPhone;
	}

	public void setSponsorPhone(String sponsorPhone) {
		this.sponsorPhone = sponsorPhone;
	}

	@Column(name = "other_sponsor_details", nullable = false)
	public String getOtherSponsorDetails() {
		return this.otherSponsorDetails;
	}

	public void setOtherSponsorDetails(String otherSponsorDetails) {
		this.otherSponsorDetails = otherSponsorDetails;
	}

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "listOfSponsors")
    public Set<ActualTournamentSponsors> getActualTournamentSponsors() {
        return actualTournamentSponsors;
    }

    public void setActualTournamentSponsors(Set<ActualTournamentSponsors> actualTournamentSponsors) {
        this.actualTournamentSponsors = actualTournamentSponsors;
	}
}
