package com.ifisolution.chesstournament.entity;
// Generated Oct 5, 2018 11:22:52 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MatchesId generated by hbm2java
 */
@Embeddable
public class MatchesId implements java.io.Serializable {

	private int playerId1;
	private int tournamentId;
	private Date matchStarDatetime;
	private int playerId2;

	public MatchesId() {
	}

	public MatchesId(int playerId1, int tournamentId, Date matchStarDatetime, int playerId2) {
		this.playerId1 = playerId1;
		this.tournamentId = tournamentId;
		this.matchStarDatetime = matchStarDatetime;
		this.playerId2 = playerId2;
	}

	@Column(name = "player_id_1", nullable = false)
	public int getPlayerId1() {
		return this.playerId1;
	}

	public void setPlayerId1(int playerId1) {
		this.playerId1 = playerId1;
	}

	@Column(name = "tournament_id", nullable = false)
	public int getTournamentId() {
		return this.tournamentId;
	}

	public void setTournamentId(int tournamentId) {
		this.tournamentId = tournamentId;
	}

	@Column(name = "match_star_datetime", nullable = false, length = 19)
	public Date getMatchStarDatetime() {
		return this.matchStarDatetime;
	}

	public void setMatchStarDatetime(Date matchStarDatetime) {
		this.matchStarDatetime = matchStarDatetime;
	}

	@Column(name = "player_id_2", nullable = false)
	public int getPlayerId2() {
		return this.playerId2;
	}

	public void setPlayerId2(int playerId2) {
		this.playerId2 = playerId2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MatchesId))
			return false;
		MatchesId castOther = (MatchesId) other;

		return (this.getPlayerId1() == castOther.getPlayerId1())
				&& (this.getTournamentId() == castOther.getTournamentId())
				&& ((this.getMatchStarDatetime() == castOther.getMatchStarDatetime())
						|| (this.getMatchStarDatetime() != null && castOther.getMatchStarDatetime() != null
								&& this.getMatchStarDatetime().equals(castOther.getMatchStarDatetime())))
				&& (this.getPlayerId2() == castOther.getPlayerId2());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlayerId1();
		result = 37 * result + this.getTournamentId();
		result = 37 * result + (getMatchStarDatetime() == null ? 0 : this.getMatchStarDatetime().hashCode());
		result = 37 * result + this.getPlayerId2();
		return result;
	}

}
