package com.ifisolution.chesstournament.entity;
// Generated Oct 5, 2018 11:22:52 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlayerTournamentParticipationId generated by hbm2java
 */
@Embeddable
public class PlayerTournamentParticipationId implements java.io.Serializable {

	private int playerId;
	private int tournamentId;

	public PlayerTournamentParticipationId() {
	}

	public PlayerTournamentParticipationId(int playerId, int tournamentId) {
		this.playerId = playerId;
		this.tournamentId = tournamentId;
	}

	@Column(name = "player_id", nullable = false)
	public int getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(int playerId) {
		this.playerId = playerId;
	}

	@Column(name = "tournament_id", nullable = false)
	public int getTournamentId() {
		return this.tournamentId;
	}

	public void setTournamentId(int tournamentId) {
		this.tournamentId = tournamentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlayerTournamentParticipationId))
			return false;
		PlayerTournamentParticipationId castOther = (PlayerTournamentParticipationId) other;

		return (this.getPlayerId() == castOther.getPlayerId())
				&& (this.getTournamentId() == castOther.getTournamentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlayerId();
		result = 37 * result + this.getTournamentId();
		return result;
	}

}
