package com.ifisolution.chesstournament.entity;
// Generated Oct 5, 2018 11:22:52 PM by Hibernate Tools 5.2.11.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * PlayerTournamentParticipation generated by hbm2java
 */
@Entity
@Table(name = "player_tournament_participation", catalog = "chess_tournament")
@JsonIgnoreProperties({"matcheses"})

public class PlayerTournamentParticipation implements java.io.Serializable {

	private PlayerTournamentParticipationId id;
	private Players players;
	private Tournaments tournaments;
	private String finalResult;
	private Set<Matches> matcheses = new HashSet<Matches>(0);

	public PlayerTournamentParticipation() {
	}

	public PlayerTournamentParticipation(PlayerTournamentParticipationId id, Players players, Tournaments tournaments,
			String finalResult) {
		this.id = id;
		this.players = players;
		this.tournaments = tournaments;
		this.finalResult = finalResult;
	}

	public PlayerTournamentParticipation(PlayerTournamentParticipationId id, Players players, Tournaments tournaments,
			String finalResult, Set<Matches> matcheses) {
		this.id = id;
		this.players = players;
		this.tournaments = tournaments;
		this.finalResult = finalResult;
		this.matcheses = matcheses;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "playerId", column = @Column(name = "player_id", nullable = false)),
			@AttributeOverride(name = "tournamentId", column = @Column(name = "tournament_id", nullable = false)) })
	public PlayerTournamentParticipationId getId() {
		return this.id;
	}

	public void setId(PlayerTournamentParticipationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "player_id", nullable = false, insertable = false, updatable = false)
	public Players getPlayers() {
		return this.players;
	}

	public void setPlayers(Players players) {
		this.players = players;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tournament_id", nullable = false, insertable = false, updatable = false)
	public Tournaments getTournaments() {
		return this.tournaments;
	}

	public void setTournaments(Tournaments tournaments) {
		this.tournaments = tournaments;
	}

	@Column(name = "final_result", nullable = false)
	public String getFinalResult() {
		return this.finalResult;
	}

	public void setFinalResult(String finalResult) {
		this.finalResult = finalResult;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "playerTournamentParticipation")
	public Set<Matches> getMatcheses() {
		return this.matcheses;
	}

	public void setMatcheses(Set<Matches> matcheses) {
		this.matcheses = matcheses;
	}

}
