package com.ifisolution.chesstournament.entity;
// Generated Oct 5, 2018 11:22:52 PM by Hibernate Tools 5.2.11.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * RefRankingCodes generated by hbm2java
 */
@Entity
@Table(name = "ref_ranking_codes", catalog = "chess_tournament")
@JsonIgnoreProperties({"playerses"})

public class RefRankingCodes implements java.io.Serializable {

	private Integer rankingCode;
	private String rankingDescription;
	private Set<Players> playerses = new HashSet<Players>(0);

	public RefRankingCodes() {
	}

	public RefRankingCodes(String rankingDescription) {
		this.rankingDescription = rankingDescription;
	}

	public RefRankingCodes(String rankingDescription, Set<Players> playerses) {
		this.rankingDescription = rankingDescription;
		this.playerses = playerses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ranking_code", unique = true, nullable = false)
	public Integer getRankingCode() {
		return this.rankingCode;
	}

	public void setRankingCode(Integer rankingCode) {
		this.rankingCode = rankingCode;
	}

	@Column(name = "ranking_description", nullable = false)
	public String getRankingDescription() {
		return this.rankingDescription;
	}

	public void setRankingDescription(String rankingDescription) {
		this.rankingDescription = rankingDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refRankingCodes")
	public Set<Players> getPlayerses() {
		return this.playerses;
	}

	public void setPlayerses(Set<Players> playerses) {
		this.playerses = playerses;
	}

}
