/*
 * Created on 2018-10-06 ( Date ISO 2018-10-06 - Time 10:44:39 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package com.ifisolution.chesstournament.service;

import com.ifisolution.chesstournament.entity.ActualTournamentSponsors;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.List;

public interface ActualTournamentSponsorsService {

    ActualTournamentSponsors getOne(Integer sponsorId, Integer tournamentsId);

    List<ActualTournamentSponsors> findAll();

    Page<ActualTournamentSponsors> findAll(Pageable pageable);

    Boolean delete(Integer sponsorId, Integer tournamentsId);

    ActualTournamentSponsors create(ActualTournamentSponsors actualTournamentSponsors);

    ActualTournamentSponsors update(ActualTournamentSponsors actualTournamentSponsors);

    Boolean exist(ActualTournamentSponsors actualTournamentSponsors);

}

