/*
 * Created on 2018-10-05 ( Date ISO 2018-10-05 - Time 15:49:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package com.ifisolution.chesstournament.service;


import com.ifisolution.chesstournament.entity.ChessClubs;
import com.ifisolution.chesstournament.repository.ChessClubsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import javax.transaction.Transactional;
import java.util.List;

@Service
@Transactional
public class ChessClubsServiceImpl implements ChessClubsService {

    @Autowired
    private ChessClubsRepository chessClubsRepository;

    @Override
    public ChessClubs getOne(Integer clubId) {
        return chessClubsRepository.findById(clubId).get();
    }

    @Override
    public Boolean delete(Integer clubId) {
        if (chessClubsRepository.getOne(clubId) != null) {
            chessClubsRepository.deleteById(clubId);
            return true;
        }
        return false;
    }

    @Override
    public ChessClubs create(ChessClubs chessClubs) {
        return chessClubsRepository.save(chessClubs);
    }

    @Override
    public ChessClubs update(ChessClubs chessClubsToUpdate) {
//        ChessClubs chessClubs = chessClubsRepository.getOne(chessClubsToUpdate.getClubId());


        return chessClubsRepository.save(chessClubsToUpdate);
    }

    @Override
    public Boolean exist(ChessClubs chessClubs) {
        return chessClubsRepository.existsById(chessClubs.getClubId());
    }

    @Override
    public List<ChessClubs> findAll() {
        return chessClubsRepository.findAll();
    }

    @Override
    public Page<ChessClubs> findAll(Pageable pageable) {
        return chessClubsRepository.findAll(pageable);
    }
}





