/*
 * Created on 2018-10-05 ( Date ISO 2018-10-05 - Time 15:49:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifisolution.chesstournament.service;

import com.ifisolution.chesstournament.entity.ChessClubs;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface ChessClubsService {

	ChessClubs getOne(Integer clubId);

	List<ChessClubs> findAll();

	Page<ChessClubs> findAll(Pageable pageable);

	Boolean delete(Integer clubId);

	ChessClubs create(ChessClubs chessClubs);

	ChessClubs update(ChessClubs chessClubs);

	Boolean exist(ChessClubs chessClubs);

}

