/*
 * Created on 2018-10-05 ( Date ISO 2018-10-05 - Time 15:49:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifisolution.chesstournament.service;

import com.ifisolution.chesstournament.entity.ListOfSponsors;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface ListOfSponsorsService {

	ListOfSponsors getOne(Integer sponsorId);

	List<ListOfSponsors> findAll();

	Page<ListOfSponsors> findAll(Pageable pageable);

	Boolean delete(Integer sponsorId);

	ListOfSponsors create(ListOfSponsors listOfSponsors);

	ListOfSponsors update(ListOfSponsors listOfSponsors);

	Boolean exist(ListOfSponsors listOfSponsors);

}

