/*
 * Created on 2018-10-04 ( Date ISO 2018-10-04 - Time 22:45:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifisolution.chesstournament.service;

import com.ifisolution.chesstournament.entity.Matches;

import java.util.Date;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface MatchesService {

	Matches getOne(Date matchStarDatetime, Integer playerId1, Integer tournamentId, Integer playerId2);

	List<Matches> findAll();

	Page<Matches> findAll(Pageable pageable);

	Boolean delete(Date matchStarDatetime, Integer playerId1, Integer tournamentId, Integer playerId2);

	Matches create(Matches matches);

	Matches update(Matches matches);

	Boolean exist(Matches matches);

}

