/*
 * Created on 2018-10-05 ( Date ISO 2018-10-05 - Time 15:49:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifisolution.chesstournament.service;

import com.ifisolution.chesstournament.entity.PlayerTournamentParticipation;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface PlayerTournamentParticipationService {

	PlayerTournamentParticipation getOne(Integer playerId, Integer tournamentId);

	List<PlayerTournamentParticipation> findAll();

	Page<PlayerTournamentParticipation> findAll(Pageable pageable);

	Boolean delete(Integer playerId, Integer tournamentId);

	PlayerTournamentParticipation create(PlayerTournamentParticipation playerTournamentParticipation);

	PlayerTournamentParticipation update(PlayerTournamentParticipation playerTournamentParticipation);

	Boolean exist(PlayerTournamentParticipation playerTournamentParticipation);

}

