/*
 * Created on 2018-10-05 ( Date ISO 2018-10-05 - Time 15:49:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifisolution.chesstournament.service;

import com.ifisolution.chesstournament.entity.Players;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface PlayersService {

	Players getOne(Integer playerId);

	List<Players> findAll();

	Page<Players> findAll(Pageable pageable);

	Boolean delete(Integer playerId);

	Players create(Players players);

	Players update(Players players);

	Boolean exist(Players players);

}

