/*
 * Created on 2018-10-05 ( Date ISO 2018-10-05 - Time 15:49:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifisolution.chesstournament.service;

import com.ifisolution.chesstournament.entity.RefResultCodes;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface RefResultCodesService {

	RefResultCodes getOne(Integer resultCode);

	List<RefResultCodes> findAll();

	Page<RefResultCodes> findAll(Pageable pageable);

	Boolean delete(Integer resultCode);

	RefResultCodes create(RefResultCodes refResultCodes);

	RefResultCodes update(RefResultCodes refResultCodes);

	Boolean exist(RefResultCodes refResultCodes);

}

