/*
 * Created on 2018-10-05 ( Date ISO 2018-10-05 - Time 15:49:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifisolution.chesstournament.service;

import com.ifisolution.chesstournament.entity.Tournaments;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface TournamentsService {

	Tournaments getOne(Integer tournamentId);

	List<Tournaments> findAll();

	Page<Tournaments> findAll(Pageable pageable);

	Boolean delete(Integer tournamentId);

	Tournaments create(Tournaments tournaments);

	Tournaments update(Tournaments tournaments);

	Boolean exist(Tournaments tournaments);

}

