/*
 * Created on 2018-10-06 ( Date ISO 2018-10-06 - Time 10:45:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package com.ifisolution.chesstournament.repository;

import com.ifisolution.chesstournament.entity.ActualTournamentSponsors;
import com.ifisolution.chesstournament.entity.ActualTournamentSponsorsId;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for ActualTournamentSponsors.
 *
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface ActualTournamentSponsorsRepository extends JpaRepository<ActualTournamentSponsors, ActualTournamentSponsorsId> {
}
