/*
 * Created on 2018-10-04 ( Date ISO 2018-10-04 - Time 22:45:21 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifisolution.chesstournament.repository;

import com.ifisolution.chesstournament.entity.ListOfSponsors;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for ListOfSponsors.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface ListOfSponsorsRepository  extends JpaRepository<ListOfSponsors, Integer> {}