/*
 * Created on 2018-10-04 ( Date ISO 2018-10-04 - Time 22:45:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifisolution.chesstournament.repository;

import com.ifisolution.chesstournament.entity.PlayerTournamentParticipation;
import com.ifisolution.chesstournament.entity.PlayerTournamentParticipationId;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for PlayerTournamentParticipation.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface PlayerTournamentParticipationRepository  extends JpaRepository<PlayerTournamentParticipation, PlayerTournamentParticipationId> {}
